// Create a custom Cloud9 runner - similar to the Sublime build system
// For more information see http://docs.aws.amazon.com/console/cloud9/create-run-config
{
    "cmd" : [
        "npx", "webpack", "serve",
        "--content-base", "src",
        "--mode", "development",
        "--inline",
        "--public", "${C9_PID}.vfs.cloud9.ap-northeast-1.amazonaws.com"
        ],
    "info" : "webpack started",
    "env" : {},
    "selector" : "source.ext"
}